import com.ponuing.GenerateChangelogTask
import com.ponuing.UpdateDependenciesTask

plugins {
    id 'net.fabricmc.fabric-loom' version '1.16-SNAPSHOT'
    id 'maven-publish'
    id 'com.github.breadmoirai.github-release' version '2.5.2'
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}


repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

tasks.register("updateModDependencies", UpdateDependenciesTask) {
    mcVersion.set(project.property("minecraft_version").toString())
    loader.set("fabric")
}

def canPublish = System.getenv("RELEASE")?.toBoolean() ?: false

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
            version = project.mod_version

            pom {
                name = "XpBottle Grabber"
                description = "A server side mod for collecting experience in bottles for Fabric ${project.minecraft_version}."
                url = "https://github.com/ponuing/XpBottleGrabber"
                licenses {
                    license {
                        name = "LGPL-3.0"
                        url = "https://opensource.org/license/lgpl-3-0"
                    }
                }
                developers {
                    developer {
                        name = "ponuing"
                        url = "https://github.com/ponuing/XpBottleGrabber"
                    }
                }
                scm {
                    connection = "scm:git:git://github.com/ponuing/XpBottleGrabber.git"
                    developerConnection = "scm:git:git://github.com/ponuing/XpBottleGrabber.git"
                    url = "https://github.com/ponuing/XpBottleGrabber"
                }
            }
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
        if (!System.getenv().containsKey("CI")) {
            mavenLocal()
        }

        if (canPublish) {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/ponuing/XpBottleGrabber")
                credentials {
                    username = System.getenv("GITHUB_ACTOR")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}
def lastTagEnv = System.getenv("PREVIOUS_TAG")
def lastTagValue = (lastTagEnv == null || lastTagEnv == "NONE") ? null : lastTagEnv
def newTagValue = System.getenv("NEW_TAG") ?: "v${project.version}"
if (canPublish) {
    def releaseTypeName = project.property("release_type") == "release"
            ? "STABLE"
            : project.property("release_type") == "beta"
            ? "BETA"
            : "ALPHA"

    TaskProvider<GenerateChangelogTask> generateChangelogTask = null

    if (lastTagValue != null) {
        def changelogHeader = null
        def addonProp = project.findProperty("changelogHeaderAddon")?.toString()
        if (addonProp != null && !addonProp.isBlank()) {
            changelogHeader = addonProp
        }

        def changelogFile = rootProject.file("changelogs/${project.property("mod_version")}.md")
        def changelogFileText = changelogFile.exists() ? changelogFile.text : null

        generateChangelogTask = tasks.register("generateChangelog", GenerateChangelogTask) {
            lastTag.set(lastTagValue)
            newTag.set(newTagValue)
            githubUrl.set("https://github.com/ponuing/XpBottleGrabber")
            prefixFilters.set(project.property("changelog_filter").toString().split(",") as List)

            prologue.set([changelogHeader, changelogFileText].findAll { it != null }.join("\n\n"))
        }
    }

    def changelogTextProvider = generateChangelogTask != null
            ? providers.provider { generateChangelogTask.get().changelogFile.get().asFile.text }
            : providers.provider { "No Changelog Generated" }

    tasks.named("githubRelease").configure {
        if (generateChangelogTask != null) {
            dependsOn(generateChangelogTask)
        }

        authorization = System.getenv("GITHUB_TOKEN")?.with { "Bearer $it" }
        owner = project.property("github_owner").toString()
        repo = project.property("github_repo").toString()
        tagName = newTagValue
        releaseName = "${project.property("mod_name")} $newTagValue"
        targetCommitish = System.getenv("GITHUB_REF_NAME") ?: "HEAD"
        releaseAssets.from(
                tasks.named("jar").get().outputs.files,
                tasks.named("sourcesJar").get().outputs.files,
        )
        subprojects.forEach {
            releaseAssets.from(
                    it.tasks.named("jar").get().outputs.files,
                    it.tasks.named("sourcesJar").get().outputs.files,
            )
        }

        body = changelogTextProvider
    }

    if (["CURSEFORGE_TOKEN", "MODRINTH_TOKEN"].any { System.getenv().containsKey(it) }) {
        publishMods {
            changelog = changelogTextProvider
            def enumValue = type.getType().enumConstants.find { it.name() == releaseTypeName }
            type.set(enumValue)
            modLoaders.add("fabric")
            modLoaders.add("quilt")
            file = tasks.named("jar").flatMap { it.archiveFile }

            if (System.getenv().containsKey("CURSEFORGE_TOKEN") || dryRun.get()) {
                curseforge {
                    projectId = "1557274"
                    accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
                    project.property("game_versions_curse").toString().split(",").each {
                        minecraftVersions.add(it)
                    }
                    displayName.set("${project.property("prefix")} ${project.property("mod_name")} ${project.version}")
                    requires("fabric-api")
                }
            }

            if (System.getenv().containsKey("MODRINTH_TOKEN") || dryRun.get()) {
                modrinth {
                    accessToken = providers.environmentVariable("MODRINTH_TOKEN")
                    projectId = "Z2yJzHom"
                    project.property("game_versions_mr").toString().split(",").each {
                        minecraftVersions.add(it)
                    }
                    displayName.set("${project.property("mod_name")} ${project.version}")
                    requires("fabric-api")
                }
            }
        }
    }
}
