# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.4
# Mod Properties
mod_version=1.0
maven_group=com.battiboom1
archives_base_name=xpbottlegrabber
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.140.2+1.21.11
# Publishing
game_versions_mr=1.21.11
game_versions_curse=1.21.11

prefix=[1.21.11]
release_type=release
changelog_filter=[feat],[fix],[change],[update],[docs],[translations]
mod_name=XpBottle Grabber
github_owner=ponuing
github_repo=XpBottleGrabber
github_url=https://github.com/ponuing/XpBottleGrabber