# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.18.4
# Mod Properties
mod_version=1.1
maven_group=com.battiboom1
archives_base_name=XpBottleGrabber
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.150.0+26.1.2

# Publishing
game_versions_mr=26.1,26.1.1,26.1.2
game_versions_curse=26.1,26.1.1,26.1.2

prefix=[26.1]
release_type=release
changelog_filter=[feat],[fix],[change],[update],[docs],[translations]
mod_name=XpBottle Grabber
github_owner=ponuing
github_repo=XpBottleGrabber
github_url=https://github.com/ponuing/XpBottleGrabber
